import type { Metadata } from "next";
import { Ubuntu_Sans } from "next/font/google";
import "./globals.css";

const ubuntuSans = Ubuntu_Sans({
  weight: ["500", "600"],
  style: ["normal"],
      subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Onboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body 
          className={`${ubuntuSans.className}  antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
